apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer-secret
data:
  host: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
---
apiVersion: vance.io/v1alpha1
kind: Connector
metadata:
  name: rabbitmq-sample
spec:
  # TODO(user): Add fields here
  exposePort: 8080
  containers:
    - name: rabbitmq-connector-sample
      image: jeffhollan/rabbitmq-client:dev
      imagePullPolicy: Always
      command:
        - receive
      args:
        - "amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672"
  secretRef: rabbitmq-consumer-secret
  scalingRule:
    customScaling:
      triggers:
        - type: rabbitmq
          metadata:
            queueName: hello
            mode: QueueLength
            value: "50"
          secretRef: rabbitmq-consumer-secret