apiVersion: vance.io/v1alpha1
kind: Connector
metadata:
  name: webhook-sample
spec:
  # TODO(user): Add fields here
  image: tomcat:8.0.18-jre8
  exposePort: 8080
  scalingRule:
    minReplicaCount: 0
    httpScaling:
      host: myhost.com
      pendingRequests: 10